### ISSUE TITLE
No module named 'pkg_ressources'

### ISSUE THREAD

**Issue by maxi07** [smarie/python-genbadge#34] opened 2023-10-25 21:16 UTC
After installing with `pip install genbadge[all]`, running any `genbadge` command gives the following error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Scripts\genbadge.exe\__main__.py", line 4, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\genbadge\__init__.py", line 5, in <module>    
    from .utils_badge import Badge
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\genbadge\utils_badge.py", line 20, in <module>
    from pkg_resources import resource_string, resource_filename       
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by smarie** [comment] 2023-11-10 20:30
Thanks @maxi07 for reporting ! This seems to be a refined duplicate of #32 .

**Closed by smarie** 2023-11-10 20:30 UTC
